-- ClickHouse schema converted from MySQL pdb_schema
-- Engine: ReplacingMergeTree with explicit version column
-- ORDER BY: natural unique key per table

-- ─────────────────────────────────────────────
-- pdb_companies
-- ReplacingMergeTree(last_updated)
-- ORDER BY record_hash
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_companies
(
    id                      Int64,
    record_hash             String,
    record_hash2            Nullable(String),
    record_hash3            Nullable(String),
    company_type            LowCardinality(String),
    name                    Nullable(String),
    duns                    Nullable(String),
    address                 Nullable(String),
    phone_researched        Nullable(String),
    city                    Nullable(String),
    state                   Nullable(String),
    county                  Nullable(String),
    country                 Nullable(String),
    postal_code             Nullable(String),
    parent_name             Nullable(String),
    web_address             Nullable(String),
    dnb_sales_value         Nullable(Float64),
    dnb_trade_style         Nullable(String),
    sic                     Nullable(String),
    naics                   Nullable(String),
    latitude                Nullable(String),
    longitude               Nullable(String),
    line_of_business        Nullable(String),
    no_of_employees         Nullable(String),
    google_cust_name        Nullable(String),
    google_address          Nullable(String),
    google_city             Nullable(String),
    google_state            Nullable(String),
    google_country          Nullable(String),
    google_postal_code      Nullable(String),
    google_phone_researched Nullable(String),
    google_web_address      Nullable(String),
    last_updated            DateTime         DEFAULT now(),
    last_updated_copy       DateTime         DEFAULT now(),
    system_count            Int32            DEFAULT 0,
    system_ids              Nullable(String),
    system_names            Nullable(String),
    services                Nullable(String),
    sic_desc                Nullable(String),
    naics_desc              Nullable(String),
    meta                    Nullable(String),  -- JSON stored as String
    total_sales             Nullable(Float32),
    total_cost              Nullable(Float32),
    in_cddb                 Int8             DEFAULT 0,
    is_cddb_client          Int8             DEFAULT 0,
    interlynx_call_host     Nullable(String),
    interlynx_rep           Nullable(String),
    interlynx_am            Nullable(String),
    interlynx_company_type  Nullable(String),
    searched_on_google      LowCardinality(String) DEFAULT 'No',
    is_active               Int8             DEFAULT 0,
    last_record_status      Int8             DEFAULT 0,
    is_appended             Int8             DEFAULT 1,
    meta_data               Nullable(String)   -- JSON stored as String
)
ENGINE = ReplacingMergeTree(last_updated)
ORDER BY record_hash
SETTINGS index_granularity = 8192;


-- ─────────────────────────────────────────────
-- pdb_companies_systemwise
-- ReplacingMergeTree(date_added)
-- ORDER BY (system_id, system_unique_id, company_type, table_name, service_type)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_companies_systemwise
(
    id                          Int64,
    is_dedupe_global            Nullable(Int32),
    dedupe_global_connect_id    Nullable(String),
    dupe_global_total_cost      Nullable(Float64),
    dupe_global_total_sales     Nullable(Float64),
    duns_global_count           Nullable(Int32),
    company_id                  Int64            DEFAULT 0,
    record_hash                 Nullable(String),
    record_hash2                Nullable(String),
    record_hash3                Nullable(String),
    ils_unique_key              Nullable(String),
    ils_unique_duns             Nullable(String),
    table_name                  String           DEFAULT '',
    service_type                String           DEFAULT '',
    company_type                String           DEFAULT '',
    system_id                   Int32            DEFAULT 0,
    system_unique_id            Int32            DEFAULT 0,
    system_name                 Nullable(String),
    client_specific_name        Nullable(String),
    customer_unique_key         Nullable(String),
    dnb_name                    Nullable(String),
    duns                        Nullable(String),
    address                     Nullable(String),
    phone_researched            Nullable(String),
    city                        Nullable(String),
    state                       Nullable(String),
    county                      Nullable(String),
    country                     Nullable(String),
    postal_code                 Nullable(String),
    parent_name                 Nullable(String),
    web_address                 Nullable(String),
    dnb_sales_value             Nullable(Float64),
    dnb_trade_style             Nullable(String),
    sic                         Nullable(String),
    naics                       Nullable(String),
    latitude                    Nullable(String),
    longitude                   Nullable(String),
    line_of_business            Nullable(String),
    no_of_employees             Nullable(String),
    google_cust_name            Nullable(String),
    google_address              Nullable(String),
    google_city                 Nullable(String),
    google_state                Nullable(String),
    google_country              Nullable(String),
    google_postal_code          Nullable(String),
    google_phone_researched     Nullable(String),
    google_web_address          Nullable(String),
    lead_source_1               Nullable(String),
    lead_source_2               Nullable(String),
    lead_source_3               Nullable(String),
    lead_source_4               Nullable(String),
    last_updated                DateTime         DEFAULT now(),
    system_count                Nullable(Int32),
    deleted_tracker_id          String           DEFAULT '0',
    total_sales                 Nullable(Float64),
    total_cost                  Nullable(Float64),
    date_added                  DateTime         DEFAULT now(),
    mapped_on                   Nullable(DateTime),
    client_type                 Nullable(Int32),
    distributor_id              Nullable(Int64),
    distributor_name            Nullable(String),
    sic_desc                    Nullable(String),
    naics_desc                  Nullable(String),
    solr_synced                 Int8             DEFAULT 0,
    is_cddb_client              Int8             DEFAULT 0,
    interlynx_call_host         Nullable(String),
    interlynx_rep               Nullable(String),
    interlynx_am                Nullable(String),
    interlynx_company_type      Nullable(String),
    supplier_type               Nullable(String),
    researched_company_name     Nullable(String),
    is_company_mapped           Int64            DEFAULT 0,
    searched_on_google          String           DEFAULT 'No',
    interlynx_name              Nullable(String),
    is_rep                      Int8             DEFAULT 0,
    meta_data                   Nullable(String),  -- JSON stored as String
    company_description         Nullable(String),
    company_keywords            Nullable(String),
    sync_data_to_system_flag    Int32            DEFAULT 0,
    meta                        Nullable(String),  -- JSON stored as String
    total_records               Nullable(Int32),
    total                       Nullable(Decimal(15, 2)),
    total_quote_value           Nullable(Decimal(15, 2)),
    total_sale_value            Nullable(Decimal(15, 2)),
    total_cost_value            Nullable(Decimal(15, 2))
)
ENGINE = ReplacingMergeTree(date_added)
ORDER BY (system_id, system_unique_id, company_type, table_name, service_type)
SETTINGS index_granularity = 8192;


-- ─────────────────────────────────────────────
-- pdb_notes
-- ReplacingMergeTree(id)
-- ORDER BY id
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_notes
(
    id                                  Int32,
    services                            Nullable(String),
    notes                               Nullable(String),
    contacts                            Nullable(String),
    company_id                          Nullable(Int32),
    note_date                           Nullable(String),
    submitted_by                        Nullable(String),
    note_category                       Nullable(String),
    tagged_systems                      Nullable(String),
    tagged_note_category                Nullable(String),
    note_rating                         String,
    note_feedback_comment               Nullable(String),
    followup_note_id                    Int32            DEFAULT 0,
    followup_note_category              Nullable(String),
    followup_note_category_type         Nullable(String),
    followup_note_category_conference   Nullable(String),
    followup_note_category_referral     Nullable(String)
)
ENGINE = ReplacingMergeTree(id)
ORDER BY id
SETTINGS index_granularity = 8192;


-- ─────────────────────────────────────────────
-- pdb_leads
-- ReplacingMergeTree(updated_at)
-- ORDER BY (system_id, system_unique_id, company_type)
-- NEW COLUMNS: system_unique_id, updated_at
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_leads
(
    id                          Int64,
    system_id                   Int32            DEFAULT 0,
    system_unique_id            Int32            DEFAULT 0,   -- new
    system_name                 Nullable(String),
    company_type                String           DEFAULT '',
    distributor_id              Nullable(Int32),
    rid                         Int32,
    uid                         Int32,
    cddb_unique_id              Int32            DEFAULT 0,
    cddb_manager_name           Nullable(String),
    cddb_manager_email          Nullable(String),
    luid                        Int32,
    status                      Nullable(String) DEFAULT '20',
    send_to_name                Nullable(String),
    send_to                     Nullable(String),
    lead_type                   Nullable(String),
    lead_type_show              Nullable(String),
    distributed_date            Nullable(String),
    county                      Nullable(String),
    city                        Nullable(String),
    state                       Nullable(String),
    zip_code                    Nullable(String),
    country                     Nullable(String),
    region                      Nullable(String),
    lead_source1                Nullable(String),
    lead_source2                Nullable(String),
    lead_source3                Nullable(String),
    lead_source4                Nullable(String),
    brand                       Int32            DEFAULT 0,
    assigned_brand              Int32            DEFAULT 0,
    product                     Nullable(String) DEFAULT '0',
    assigned_product            Int32            DEFAULT 0,
    market                      Nullable(String) DEFAULT '0',
    assigned_market             Int32            DEFAULT 0,
    current_id                  Nullable(Int32),
    closed_date                 Nullable(String),
    closedate_mid               Nullable(String),
    forward_to                  Nullable(String),
    forword_id                  Nullable(String) DEFAULT '0',
    forward_by_rid              Nullable(String) DEFAULT '0',
    forward_by_uid              Nullable(String) DEFAULT '0',
    order_amount                Nullable(String),
    order_desc                  Nullable(String),
    post_reminder_date          Nullable(String),
    reminder_days               Nullable(String) DEFAULT '0',
    reminder_cnt                Int32            DEFAULT 0,
    reminder_date               Nullable(String),
    reminder_last_sent_date     Nullable(String),
    reminder_desc               Nullable(String),
    other_value                 Nullable(String),
    no_pot_value                Nullable(String),
    lead_person_name            Nullable(String),
    forwarded_comments          Nullable(String),
    posted_comments             Nullable(String),
    open_reason                 Nullable(String),
    lead_source_repr            Nullable(String),
    review_interlynx            Nullable(String) DEFAULT '0',
    mscode                      Nullable(String),
    stprod_code                 Nullable(String),
    browser_name                Nullable(String),
    browser_version             Nullable(String),
    browser_platform            Nullable(String),
    server_ip                   Nullable(String),
    system_ip                   Nullable(String),
    mobile_posted               Nullable(String),
    quoted_amount               Nullable(String),
    lead_date_time              Nullable(DateTime),
    existing_customer           Nullable(String),
    new_costomer                Nullable(String),
    cust_type_other             Nullable(String),
    no_pot_competitor           Nullable(String),
    old_uid                     Nullable(Int32),
    old_send_to                 Nullable(String),
    received_date_time          Nullable(String),
    dont_know                   Nullable(String),
    good_lead_value             Nullable(String),
    unable_to_reach_value       Nullable(String),
    not_my_lead_value           Nullable(String),
    not_mine_brand              Nullable(String),
    other_reason                Nullable(String),
    posted_reason               Nullable(String) DEFAULT '',
    annual_potential            Nullable(String),
    sic                         Nullable(String),
    naics                       Nullable(String),
    supplier_sent               Nullable(String),
    auto_sent                   Nullable(String),
    send_lead_date_time         Nullable(String),
    first_post_date_time        Nullable(String),
    last_post_lead_date_time    Nullable(String),
    first_opend_date_time       Nullable(String),
    last_opend_date_time        Nullable(String),
    last_forward_lead_date_time Nullable(String),
    uploaded_from               Nullable(String),
    direct_account              Nullable(String) DEFAULT '0',
    forwarded_date              Nullable(String),
    remind_me_date_time         Nullable(String),
    lead_hash_key               String,
    can_post                    Nullable(String) DEFAULT 'Yes',
    demo_lead                   Nullable(String) DEFAULT 'No',
    old_id                      Nullable(Int32),
    csr_id                      Nullable(Int64),
    flash_report                LowCardinality(String) DEFAULT 'No',
    tm_id                       Int32            DEFAULT 0,
    sub_status_id               Int32            DEFAULT 0,
    mql_lead                    LowCardinality(String) DEFAULT 'No',
    time_to_view                String           DEFAULT '0',
    time_to_close               String           DEFAULT '0',
    time_to_first_post          String           DEFAULT '0',
    brandname                   Nullable(String),
    product_name                Nullable(String),
    market_name                 Nullable(String),
    internal_market             Nullable(String),
    internal_sub_market         Nullable(String),
    sic_name                    Nullable(String),
    sic_root                    Nullable(String),
    sic_root_name               Nullable(String),
    sic_group                   Nullable(String),
    sic_group_name              Nullable(String),
    naics_name                  Nullable(String),
    naics_root                  Nullable(String),
    naics_root_name             Nullable(String),
    naics_group                 Nullable(String),
    naics_group_name            Nullable(String),
    status_name                 Nullable(String),
    sub_status                  Nullable(String),
    sources                     Nullable(String),  -- JSON stored as String
    business_name               Nullable(String),
    address                     Nullable(String),
    contact                     Nullable(String),
    email                       Nullable(String),
    webaddr                     Nullable(String),
    phone                       Nullable(String),
    phone_researched            Nullable(String),
    lat                         Nullable(String),
    lon                         Nullable(String),
    assigned_manager_name       Nullable(String),
    customer_type               Nullable(String),
    lead_comments               Nullable(String),
    posted_comments_2           Nullable(String),
    forwarded_date_2            Nullable(Date),
    lead_date                   Nullable(Date),
    order_amount_2              Nullable(Float32),
    quote_amount                Nullable(Float32),
    lead_hash                   Nullable(String),
    created_at                  DateTime         DEFAULT now(),
    updated_at                  DateTime         DEFAULT now()  -- new
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (system_id, system_unique_id, company_type)
SETTINGS index_granularity = 8192;


-- ─────────────────────────────────────────────
-- pdb_pos_sales
-- ReplacingMergeTree(updated_at)
-- ORDER BY (system_id, system_unique_id, company_type)
-- NEW COLUMNS: system_unique_id, company_type (non-null), updated_at
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_pos_sales
(
    id                      Int32,
    company_type            String           DEFAULT '',
    system_id               Int32            DEFAULT 0,
    system_unique_id        Int32            DEFAULT 0,   -- new
    system_name             Nullable(String),
    uid                     Nullable(Int32),
    distributor_id          Nullable(Int32),
    temp_distributor_id     Int32            DEFAULT 0,
    cust_unique_key         Nullable(String),
    cddb_unique_id          Nullable(Int32),
    cddb_manager_name       Nullable(String),
    cddb_manager_email      Nullable(String),
    dist_account_number     Nullable(String),
    invoice_number          Nullable(String),
    invoice_date            Nullable(String),
    cust_account_number     Nullable(String),
    quantity                Decimal(20, 2)   DEFAULT 0,
    total_sales_value       Decimal(20, 2)   DEFAULT 0,
    total_cost_value        Decimal(20, 2)   DEFAULT 0,
    part_number_actual      Nullable(String),
    year                    Nullable(UInt16),
    month                   Nullable(String),
    part_number             Nullable(String),
    toplevel_family_1       Nullable(String),
    toplevel_family_2       Nullable(String),
    toplevel_family_3       Nullable(String),
    toplevel_family_4       Nullable(String),
    product_id              Nullable(Int32),
    brand                   Nullable(String),
    part_number_submitted   Nullable(String),
    branch                  Nullable(String),
    sic                     Nullable(String),
    naics                   Nullable(String),
    country                 Nullable(String),
    region                  Nullable(String),
    pos_batch_id            Nullable(String),
    date_upload             Nullable(Date),
    is_rebated              Int8             DEFAULT 0,
    date_recieved           String           DEFAULT '',
    cust_duns_id            Nullable(String),
    unit_cost               Nullable(Decimal(20, 2)),
    unit_resale             Nullable(Decimal(20, 2)),
    provided_customer_nbr   Nullable(String),
    sales_unique_key        Nullable(String),
    fix                     Nullable(String),
    part_updated_date       Nullable(String),
    sales_rep               Nullable(String),
    csv_name                Nullable(String),
    uom                     Nullable(String),
    match_criteria          Nullable(String),
    ship_to_commission      Nullable(String),
    ship_to_unit_price      Nullable(String),
    ship_to_unit_cost       Nullable(String),
    ship_to_pct             Nullable(String),
    unit_cost_original      Nullable(String),
    quantity_original       Nullable(String),
    prod_group              Nullable(String),
    territory_number        Nullable(String),
    tmid                    Nullable(String),
    brand_name              Nullable(String),
    product_name            Nullable(String),
    sic_name                Nullable(String),
    naics_name              Nullable(String),
    sic_group               Nullable(String),
    sic_root                Nullable(String),
    naics_group             Nullable(String),
    naics_root              Nullable(String),
    sic_text                Nullable(String),
    sic_market_name         Nullable(String),
    sic_root_name           Nullable(String),
    naics_text              Nullable(String),
    naics_market_name       Nullable(String),
    naics_root_name         Nullable(String),
    assigned_manager_company Nullable(String),
    assigned_manager_name   Nullable(String),
    customer_name           Nullable(String),
    address1                Nullable(String),
    city                    Nullable(String),
    state                   Nullable(String),
    county                  Nullable(String),
    zip                     Nullable(String),
    phone                   Nullable(String),
    web_address             Nullable(String),
    line_of_business        Nullable(String),
    parent_name             Nullable(String),
    latitude                Nullable(String),
    longitude               Nullable(String),
    is_new_customer         Int8             DEFAULT 0,
    is_new_product          Int8             DEFAULT 0,
    raw_cust_name           Nullable(String),
    raw_address             Nullable(String),
    raw_city                Nullable(String),
    raw_state               Nullable(String),
    raw_postal_code         Nullable(String),
    raw_country             Nullable(String),
    unique_key_all_fields   Nullable(String),
    updated_at              DateTime         DEFAULT now()   -- new
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (system_id, system_unique_id, company_type)
SETTINGS index_granularity = 8192;


-- ─────────────────────────────────────────────
-- pdb_quotes
-- ReplacingMergeTree(updated_at)
-- ORDER BY (system_id, system_unique_id, company_type)
-- NEW COLUMNS: system_unique_id, company_type (non-null), updated_at
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_quotes
(
    id                          Int32,
    system_id                   Int32            DEFAULT 0,
    system_unique_id            Int32            DEFAULT 0,   -- new
    system_name                 String,
    company_type                String           DEFAULT '',
    cddb_unique_id              Int32,
    distributor_id              Int32,
    cddb_manager_name           Nullable(String),
    cddb_manager_email          Nullable(String),
    rid                         Int32,
    luid                        Nullable(Int32),
    uid                         Nullable(Int32),
    address                     Nullable(String),
    assign_value                Nullable(Int32),
    brand                       Nullable(Int32),
    can_post                    Nullable(String),
    city                        Nullable(String),
    close_date                  Nullable(String),
    company                     Nullable(String),
    contact_email               Nullable(String),
    contact_name                Nullable(String),
    contact_phone               Nullable(String),
    country                     Nullable(String),
    county                      Nullable(String),
    crm_id                      Nullable(String),
    current_id                  Nullable(Int32),
    demo                        Nullable(String),
    description                 Nullable(String),
    distributed_date            Nullable(String),
    estimated_close_date        Nullable(String),
    extra_json                  Nullable(String),
    first_opend_date_time       Nullable(String),
    first_post_date_time        Nullable(String),
    forward_by_rid              Nullable(String),
    forward_to                  Nullable(String),
    forword_id                  Nullable(String),
    last_follow_up_date         Nullable(String),
    last_opend_date_time        Nullable(String),
    last_post_quote_date_time   Nullable(String),
    latitude                    Nullable(String),
    line_item_json              Nullable(String),
    longitude                   Nullable(String),
    order_amount                Nullable(String),
    other_reason                Nullable(String),
    pdf                         Nullable(String),
    posted_comments             Nullable(String),
    quantity                    Nullable(String),
    quote_creator               Nullable(String),
    quote_date                  Nullable(String),
    quote_hash_key              Nullable(String),
    quote_last_mail_sent_date   Nullable(String),
    quote_luid                  Nullable(String),
    quote_mail_sent             Nullable(String),
    quote_mail_sent_date        Nullable(String),
    quote_number                Nullable(String),
    quote_price                 Nullable(String),
    quote_sent_date_time        Nullable(DateTime),
    quote_status                Nullable(String),
    quote_type                  Nullable(String),
    quote_upload_date           Nullable(DateTime),
    quoted_sales_rep            Nullable(String),
    received_date_time          Nullable(String),
    referral_email              Nullable(String),
    referral_manager            Nullable(String),
    region                      Nullable(String),
    reminder_cnt                Nullable(Int32),
    reminder_date               Nullable(String),
    reminder_days               Nullable(String),
    reminder_last_sent_date     Nullable(String),
    send_quote_date_time        Nullable(String),
    send_to                     Nullable(String),
    state                       Nullable(String),
    status                      Int32,
    sub_reason                  Nullable(String),
    sub_status_id               Nullable(Int32),
    website                     Nullable(String),
    zip_code                    Nullable(String),
    assigned_manager_name       Nullable(String),
    brandname                   Nullable(String),
    status_name                 Nullable(String),
    sub_status                  Nullable(String),
    view_time                   Nullable(String),
    post_time                   Nullable(String),
    close_time                  Nullable(String),
    updated_at                  DateTime         DEFAULT now()   -- new
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (system_id, system_unique_id, company_type)
SETTINGS index_granularity = 8192;


-- ─────────────────────────────────────────────
-- pdb_inventory
-- ReplacingMergeTree(updated_at)
-- ORDER BY (system_id, system_unique_id, company_type)
-- NEW COLUMNS: system_unique_id, company_type (non-null), updated_at
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pdb_inventory
(
    id                      Int32,
    system_id               Int32            DEFAULT 0,
    system_unique_id        Int32            DEFAULT 0,   -- new
    system_name             Nullable(String),
    company_type            String           DEFAULT '',
    distributor_id          Nullable(Int32),
    cddb_unique_id          Nullable(Int32),
    uid                     Nullable(Int32),
    assigned_manager_name   Nullable(String),
    brand_id                Nullable(Int32),
    brand_name              Nullable(String),
    partnumber_id           Nullable(Int32),
    product_name            Nullable(String),
    product_desc            Nullable(String),
    prod_category_1         Nullable(String),
    prod_category_2         Nullable(String),
    prod_category_3         Nullable(String),
    prod_category_4         Nullable(String),
    p1                      Int32            DEFAULT 0,
    p2                      Int32            DEFAULT 0,
    p3                      Int32            DEFAULT 0,
    p4                      Int32            DEFAULT 0,
    branch                  Nullable(Int32),
    date                    Nullable(Date),
    quantity                Nullable(Int32),
    unit_cost               Nullable(Float64),
    uom                     Nullable(String),
    part_url                Nullable(String),
    date_received           Nullable(Date),
    batch_id                Int32            DEFAULT 0,
    unique_key              Nullable(String),
    uploaded_date_time      Nullable(DateTime),
    csvname                 Nullable(String),
    temp_qty                Nullable(Int32),
    total_sales             Nullable(Float64),
    total_cost              Nullable(Float64),
    total_qty               Nullable(Float32),
    no_of_cust              Nullable(Int32),
    turns                   Nullable(Float64),
    key_cust                Nullable(Int32),
    dist_acc_number         Nullable(String),
    safetyRatio             Nullable(Int32),
    manual_lead_time        Float64          DEFAULT 14,
    updated_at              DateTime         DEFAULT now()   -- new
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (system_id, system_unique_id, company_type)
SETTINGS index_granularity = 8192;
